### PR TITLE
Fix some obvious OCR-related typos.

### PR DESCRIPTION
**Pull request by ascherer**
Found some time to actually read a few pages—mostly Part 1 of the report—of the PDF, fixing obvious issues as I go along.

Greatest nuissance are the (opening) double quotes; that will be a separate—and probably huge—PR.

### CODE REVIEW

**Comment by iandennismiller** [comment]
I will take a closer look soon but I really appreciate that you're taking this on. Thank you and I look forward to that double quote PR!

**Comment by ascherer** [comment]
Apropos double quotes: Would you prefer the 7-bit TeX way with double backticks `` and double apostrophes `''` (as already used in some places) or the UTF-8 way with “ and ”? LaTeX does handle both. (Similar for single quotes.)

**Comment by iandennismiller** [comment]
I was thinking 7-bit. I like that I can enter those characters with basic vim. Do you know any pros and cons for the Unicode characters?

**Comment by ascherer** [comment]
I agree that 7-bit ASCII is preferable. Same for hyphens, en- and em-dashes.

**Comment by iandennismiller** [comment]
Thanks - then we are agreed!

**Comment by ascherer** [comment]
Please consider merging this PR. I'll open new ones for the “quotes” and for proofreading Volume 2.

**Review by iandennismiller — APPROVED** [review]
My apologies for the delay.  Once again, I am truly impressed by your attention to detail!

**Pull request merged**
