### PR TITLE
Proofread Report 2nd time cont.

### PR DESCRIPTION
**Pull request by ascherer**
~~“Factual Results” completed. About 80 pages more to proofread (plus the “quotes”).~~

Now that the major issues are fixed, the Report is almost pleasant to read.

### CODE REVIEW

**Comment by ascherer** [comment]
Home at last! I've finished the first complete round through the whole Mueller Report. Time permitting, I'll start all over again.

**Comment by iandennismiller** [comment]
I am watching this pull request closely!  It looks like it will be epic!

**Comment by ascherer** [comment]
@iandennismiller could you please merge this PR? I've completed Vol. I for the second time and would like to see these changes included before I re-read Vol. II.

**Comment by ascherer** [comment]
Done. Amazing how many types of errors needed addressing (including quite a few in the original Report).

**Comment by ascherer** [comment]
Mayday! One of the recent commits broke the table of contents: The non-automatic chapter numbers are all set to '0'. Will bisect ASAP.

**Comment by iandennismiller** [comment]
No worries! I have not merged just yet.

Would it be okay if I reviewed this as soon as you push a fix for the table of contents?

**Comment by ascherer** [comment]
Already found a solution: the 'chapter' counter has to be increased in 'main.tex' (or rather 'chapter-1.tex' etc. Will commit tomorrow.

**Comment by ascherer** [comment]
I think I'll try to address issue #36 next: https://tex.stackexchange.com/questions/816/cyrillic-in-latex

**Comment by ascherer** [comment]
@iandennismiller please review this massive heap of changes. I'll take this weekend off.

AFAICS, this PR fixes, or at least partly addresses, issues #30, #31, #33, #36, #37, #55, #65, and #69.

**Review by iandennismiller — APPROVED** [review]
I apologize for the delay.  I am going to merge all these commits now!

**Pull request merged**
